version: '3.1'
services:
  zssn:
    container_name: zssn
    image: gcr.io/neurons-be-test/zssn:latest
    ports:
      - 8080:8080
    environment:
      ENVIRONMENT: "docker"
      DB_HOST: zssndb
      DB_PORT: 3306
      DB_USER: zssn_user
      DB_PASSWORD: p@azzword
      DB_NAME: zssn

    depends_on:
      zssndb:
        condition: service_healthy

    networks:
      - zssn


  zssndb:
    container_name: zssn-db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: zssn_user
      MYSQL_PASSWORD: p@azzword
      MYSQL_DATABASE: zssn

    networks:
      - zssn

    healthcheck: # check the healthiness with the following configuration
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '--user=zssn_user', '--password=p@azzword']
      interval: 3s
      timeout: 3s
      retries: 5

networks:
  zssn:
    driver: bridge
    